version: "3.8"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pyrunner-api
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

nginx:
  build:
    context: ./nginx
    dockerfile: Dockerfile
  container_name: nginx
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - certbot-etc:/etc/letsencrypt
    - certbot-webroot:/var/www/certbot
    - ./nginx:/etc/nginx/conf.d
  depends_on:
    - backend

volumes:
  certbot-etc:
  certbot-webroot:
  mongo-data:
